AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS Lambda Function to Validate US Address

Resources:
  USAddressValidation:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      Environment:
              Variables:
                SERVICEKEY: SERVICEKEY
                ACTIVE_FLAG: ACTIVE_FLAG
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
    GetEvent:
     Type: Api
     Properties:
       Path: /address
       Method: post
